"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](overlay)\
$os\
$username\
[](bg:secondary fg:overlay)\
$directory\
[](fg:secondary bg:success)\
$git_branch\
[](fg:success bg:info)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$ocaml\
$ruby\
$lua\
$nim\
$fennel\
$elixir\
$java\
$kotlin\
$haskell\
$python\
[](fg:info bg:warning)\
[ ](fg:warning)\
$line_break$character"""

palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
error = '#eb6f92'
warning = '#f6c177'
primary = '#ebbcba'
info = '#31748f'
success = '#9ccfd8'
secondary = '#c4a7e7'

[os]
disabled = false
style = "bg:overlay fg:secondary"

[os.symbols]
NixOS = ""

[username]
show_always = true
style_user = "bg:overlay fg:secondary"
style_root = "bg:overlay fg:secondary"
format = '[ $user ]($style)'

[directory]
style = "bg:secondary fg:info"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:success"
format = '[[ $symbol $branch ](fg:secondary bg:success)]($style)'

#[git_status]
#style = "bg:success"
#format = '[[($all_status$ahead_behind )](fg:secondary bg:success)]($style)'
#up_to_date = '[ ✓ ](bg:overlay fg:secondary)'
#untracked = '[?\($count\)](bg:overlay fg:warning)'
#stashed = '[\$](bg:overlay fg:secondary)'
#modified = '[!\($count\)](bg:overlay fg:warning)'
#renamed = '[»\($count\)](bg:overlay fg:secondary)'
#deleted = '[✘\($count\)](style)'
#staged = '[++\($count\)](bg:overlay fg:warning)'
#ahead = '[⇡\(${count}\)](bg:overlay fg:success)'
#diverged = '⇕[\[](bg:overlay fg:secondary)[⇡\(${ahead_count}\)](bg:overlay fg:success)[⇣\(${behind_count}\)](bg:overlay fg:primary)[\]](bg:overlay fg:secondary)'
#behind = '[⇣\(${count}\)](bg:overlay fg:primary)'

[nodejs]
symbol = ""
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[c]
symbol = " "
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[cpp]
symbol = " "
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[rust]
symbol = ""
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[golang]
symbol = ""
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[ocaml]
symbol = ""
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[fennel]
symbol = ""
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[nim]
symbol = "󰆥"
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[ruby]
symbol = ""
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[lua]
symbol = ""
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[java]
symbol = ""
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[kotlin]
symbol = ""
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[haskell]
symbol = ""
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[python]
symbol = ""
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[elixir]
symbol = ""
style = "bg:primary"
format = '[[ $symbol( $version) ](fg:primary bg:info)]($style)'

[line_break]
disabled = true

[character]
disabled = true
